version: '3.8'

services:
  app:
    container_name: tictactoe-multiplayer
    image: fredrikjern/tictactoe-multiplayer:0.0.2
    restart: unless-stopped
    build: .
    ports:
      - "3012:3000"
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db

  db:
    container_name: db-tictactoe-multiplayer
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

volumes:
  db: