version: '3.8'

services:
  app:
    container_name: tictactoe-multiplayer
    image: fredrikjern/tictactoe-multiplayer:0.0.3
    restart: unless-stopped
    build: .
    ports:
      - "3012:3000"
    environment:
      - MONGO_URI=mongodb://root:test@db:27017
    depends_on:
      - db

  db:
    container_name: db-tictactoe-multiplayer
    image: mongo:6.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - db:/data/db

volumes:
  db: